/* SADEEM HANGAR · 03 Pipeline Hall (collect → route) + 04 Containment Vault */
(function(){
const {$,$$,esc,t,tx,num,go,register,ai,toast,allIdeas,CHALLENGES,addIdea,SOURCES,DOMAINS,ENTITIES}=H;
const E=window.EVAL;
/* gate to leave each station (proposed, pending official approval) */
const GATES=[
 {ar:"استلام عبر البوابة الواحدة وإصدار رقم مرجعي",en:"Received through the single door; reference issued"},
 {ar:"تحديد المجال ونوع المصدر والاحتياج الوطني",en:"Domain, source type and national need tagged"},
 {ar:"اجتياز فحص الازدواجية وضمن النطاق",en:"Duplicate check cleared; in scope"},
 {ar:"تأكيد مستوى الحساسية من شخص مخوّل",en:"Sensitivity level confirmed by an authorised person"},
 {ar:"إسناد إلى محفظة ومحلل",en:"Assigned to a portfolio and an analyst"},
 {ar:"اجتياز حد التقييم على المعايير الوطنية الستة",en:"Threshold met on the six national criteria"},
 {ar:"الأفضل بين الأفكار المشابهة في جدول الأفكار",en:"Best in class against similar ideas in the idea table"},
 {ar:"خطة تجربة بقياس قبل/بعد",en:"An experiment plan with a before/after measure"},
 {ar:"تسجيل النتائج وتحقيق «التوجيه قبل التنفيذ»",en:"Results recorded; guidance before execution met"},
 {ar:"اعتماد الجهة المخوّلة",en:"Approval by the authority"},
 {ar:"قبول الجهة الوطنية المختصة وتحوّلها إلى برنامج قدرة",en:"Accepted by the competent entity; becomes a capability programme"}];
const CRIT=[["need",{ar:"مواءمة الاحتياج الوطني",en:"National need alignment"}],["sov",{ar:"القيمة السيادية",en:"Sovereign value"}],["feas",{ar:"الجدوى والنضج التقني",en:"Feasibility & maturity"}],["self",{ar:"الاكتفاء الذاتي",en:"Self-sufficiency"}],["risk",{ar:"المخاطر والحساسية",en:"Risk & sensitivity"}],["quality",{ar:"جودة المدخل الفكري",en:"Quality of the input"}]];
function natScore(i){const ev=E.evaluate((i.d||"")+" "+tx(i.t),i.ch);const h=[...String(i.id)].reduce((a,c)=>a+c.charCodeAt(0),0);
  const s={need:i.ch?Math.min(100,70+h%25):45,sov:Math.min(100,50+(i.sens?25:0)+h%20),feas:ev.s.feasibility,self:Math.min(100,45+(/spare|قطع|supply|إمداد|additive|تصنيع/i.test(tx(i.t)+(i.t.en||""))?35:10)+h%15),risk:i.sens==="high"?70:ev.s.risk,quality:ev.s.clarity};
  const total=Math.round(s.need*.22+s.sov*.18+s.feas*.18+s.self*.16+(100-s.risk)*.1+s.quality*.16);return {s,total,ev}}
const words=s=>new Set(String(s||"").toLowerCase().replace(/[^\p{L}\p{N}\s]/gu," ").split(/\s+/).filter(w=>w.length>2));
function similar(text,skip){const a=words(text);return allIdeas().filter(i=>i.id!==skip).map(i=>{const b=words(tx(i.t)+" "+(i.t.en||"")+" "+(i.t.ar||"")+" "+(i.d||""));let n=0;a.forEach(w=>{if(b.has(w))n++});return {i,sim:a.size?n/Math.min(a.size,b.size||1):0}}).filter(x=>x.sim>=.34).sort((x,y)=>y.sim-x.sim).slice(0,3)}
const STEPS=[{k:"problem",l:{ar:"ما الفكرة أو المبادرة؟ ما الذي لاحظته ولماذا يهم الدولة؟",en:"What is the idea or initiative? What did you observe and why does it matter to the state?"}},{k:"evidence",l:{ar:"ما الدليل؟ أرقام، تجارب، حالات متكررة",en:"What is the evidence? Numbers, trials, repeated cases"}},{k:"root",l:{ar:"ما السبب الجذري الذي تعالجه؟",en:"What root cause does it address?"}},{k:"value",l:{ar:"ما الأثر الوطني؟ اكتفاء ذاتي، تقليل هدر أو مخاطر، قدرة جديدة",en:"What is the national impact? Self-sufficiency, less waste or risk, a new capability"}},{k:"concept",l:{ar:"ما الحل المقترح، وما مستوى نضجه، وما البديلان؟",en:"What is the proposed solution, its maturity, and two alternatives?"}}];
let sel=null,walk=null;
register("lab",{
 mount(el){
  H.head(el,{ar:"مسار سديم · 03",en:"Pipeline Hall · 03"},{ar:"من التجميع إلى التوجيه للجهة الوطنية المختصة",en:"From collection to routing to the competent national entity"},{ar:"إحدى عشرة محطة مستخرجة من وظائف مركز سديم. كل فكرة جسم على الخط، وكل بوابة تقول ما يفتح المحطة التالية. البوابات والمعايير مقترحة بانتظار الاعتماد الرسمي.",en:"Eleven stations drawn from SADEEM's functions. Every idea is an object on the line, and every gate says what opens the next station. Gates and criteria are proposed, pending official approval."});
  el.insertAdjacentHTML("beforeend",`<div class="wrap" style="padding-bottom:48px"><div class="tblWrap"><svg class="journey" id="jr" viewBox="0 0 1210 250" role="img" aria-label="SADEEM pipeline" style="min-width:760px"></svg></div>
   <p class="note" style="margin-top:8px">${esc(t("proposed"))} · ${esc(tx({ar:"الأزرق البرونزي: أفكارك · الذهبي: مصادر وطنية · الداكن: محتواة",en:"Bronze: your ideas · gold: national sources · dark: contained"}))}</p>
   <div class="grid g2" style="margin-top:18px"><div style="display:grid;gap:18px;align-content:start"><div class="panel" id="detail"></div><div class="panel"><h3>${esc(tx({ar:"الأفكار على الخط",en:"Ideas on the line"}))}<small id="iN"></small></h3><div class="ideaList" id="ideas"></div></div></div>
   <div style="display:grid;gap:18px;align-content:start"><div class="panel" id="walkP"></div><div class="panel"><h3>${esc(tx({ar:"احتياجات الدولة المعلنة",en:"Declared national needs"}))}</h3><div class="chl" id="chl"></div></div></div></div></div>`);
  const st=H.ctx.state||{};if(st.draft){walk={step:0,t:tx(st.draft.t),d:st.draft.d,area:st.draft.area||"land",src:"talent",ch:st.draft.ch||"",f:{problem:st.draft.d}}}
  if(st.openIdea)sel=st.openIdea;if(st.openCh)walk={step:0,t:"",d:"",area:"land",src:"talent",ch:st.openCh,f:{}};
  render();
  function render(){
    const ideas=allIdeas();drawJourney(ideas);
    $("#iN").textContent=num(ideas.length);
    $("#ideas").innerHTML=ideas.slice(0,16).map(i=>{const c=isContained(i);return `<button class="ideaRow" data-i="${esc(i.id)}"><i>${esc(i.id)}</i><span><b>${esc(c&&!i.mine?tx({ar:"سجل محتوى",en:"Contained record"}):tx(i.t))}</b><small>${esc(t("stage")[i.st])} · ${esc(tx(SOURCES[i.src]||i.owner))}${i.sample?" · "+tx({ar:"مثال",en:"example"}):""}</small></span><span class="tag ${c?"warn":i.st>=9?"good":i.st>=5?"sov":""}">${c?"◆":num(i.st+1)+"/11"}</span></button>`}).join("");
    $$("#ideas .ideaRow").forEach(b=>b.onclick=()=>{sel=b.dataset.i;render()});
    renderDetail(ideas);renderWalk();
    $("#chl").innerHTML=CHALLENGES.map(c=>`<div class="ch"><b>${esc(c.id)} · ${esc(tx(c.t))}</b><p>${esc(tx(c.d))}</p><div class="row"><span>${esc(tx(c.sponsor))}</span><span>${num(allIdeas().filter(i=>i.ch===c.id).length)} ${esc(tx({ar:"فكرة",en:"ideas"}))} · ${num(c.due)} ${esc(tx({ar:"يوماً",en:"days"}))}</span></div><button class="chip" data-ch="${c.id}">${esc(tx({ar:"قدّم فكرة لهذا الاحتياج",en:"Submit for this need"}))}</button></div>`).join("");
    $$("[data-ch]").forEach(b=>b.onclick=()=>{walk={step:0,t:"",d:"",area:"land",src:"talent",ch:b.dataset.ch,f:{}};render();$("#walkP").scrollIntoView({behavior:"smooth"})});
  }
  function isContained(i){return i.sens==="high"||H.DB.gate.some(x=>x.idea===i.id&&x.level==="high")}
  function drawJourney(ideas){
    const s=$("#jr");const n=11,rtl=H.L==="ar",x0=rtl?1080:60,x1=rtl?120:1140,step=(x1-x0)/(n-1);let g=`<line class="rail" x1="${Math.min(x0,x1)}" y1="160" x2="${Math.max(x0,x1)}" y2="160"/>`;
    g+=`<rect x="${x0+3*step-26}" y="20" width="52" height="170" rx="4" fill="var(--brassT)" stroke="var(--brass)" stroke-dasharray="3 3"/><text x="${x0+3*step}" y="244" style="font:600 10px var(--mono);fill:var(--brass);text-anchor:middle">${esc(tx({ar:"الاحتواء",en:"CONTAINMENT"}))}</text>`;
    for(let i=0;i<n;i++){const x=x0+i*step;const c=ideas.filter(k=>k.st===i);const on=sel&&ideas.find(k=>k.id===sel)&&ideas.find(k=>k.id===sel).st===i;
      g+=`<g class="st ${on?"on":""}" data-s="${i}"><circle cx="${x}" cy="160" r="9"/><text x="${x}" y="${i%2?206:192}">${esc(t("stage")[i])}</text>${i<n-1?`<line class="gate" x1="${x+step/2}" y1="142" x2="${x+step/2}" y2="178"/>`:""}`;
      c.slice(0,7).forEach((k,j)=>{const y=136-j*15;const w=Math.min(56,Math.max(26,tx(k.t).length*1.6));g+=`<g class="idea ${k.mine?"mine":""} ${isContained(k)?"c":""}" data-i="${esc(k.id)}"><rect x="${x-w/2}" y="${y-11}" width="${w}" height="11"/></g>`});
      if(c.length>7)g+=`<text x="${x}" y="20" style="font:10px var(--mono);fill:var(--mute);text-anchor:middle">+${num(c.length-7)}</text>`;
      g+=`</g>`}
    g+=`<text x="${rtl?x1-24:x1+24}" y="164" text-anchor="${rtl?"end":"start"}" style="font:600 10px var(--mono);fill:var(--sov)">${rtl?"← ":""}${esc(tx({ar:"جهة مختصة",en:"ENTITY"}))}${rtl?"":" →"}</text>`;
    s.innerHTML=g;$$("#jr .idea").forEach(e=>e.onclick=()=>{sel=e.dataset.i;render()});$$("#jr .st circle").forEach(e=>e.onclick=()=>{ai.set({object:"station",state:+e.parentNode.dataset.s})});
  }
  function renderDetail(ideas){
    const i=ideas.find(x=>x.id===sel);const box=$("#detail");
    if(!i){box.innerHTML=`<h3>${esc(tx({ar:"سجل الفكرة",en:"Idea record"}))}</h3><p class="mute">${esc(tx({ar:"اختر فكرة على الخط أو من القائمة.",en:"Select an idea on the line or from the list."}))}</p>`;return}
    const cont=isContained(i);const gate=H.DB.gate.find(x=>x.idea===i.id);
    if(cont&&!i.mine){box.innerHTML=`<h3>${esc(i.id)} · ${esc(tx({ar:"سجل محتوى",en:"Contained record"}))}</h3><div class="vault sealed" style="min-height:180px"><div class="seal"><div><b>CONTAINED · محتواة</b><span>${esc(gate?gate.ref:"SD-VAULT")} · ${esc(t("stage")[i.st])}</span></div></div></div><p class="note" style="margin-top:10px">${esc(tx({ar:"المحتوى محجوب عن هذا العرض. يظهر المرجع والمحطة فقط، ولا يُرسل النص إلى أي نموذج خارجي.",en:"Content withheld from this view. Only the reference and station show, and the text is never sent to an external model."}))}</p>`;ai.set({object:"contained",state:{i}});return}
    const ns=natScore(i);const twins=similar(tx(i.t)+" "+(i.d||""),i.id);const peers=allIdeas().filter(x=>x.id!==i.id&&x.area===i.area&&x.st>=5).slice(0,3);
    box.innerHTML=`<h3>${esc(i.id)} · ${esc(tx(i.t))}<small>${esc(tx(SOURCES[i.src]||i.owner))} · ${esc(tx(DOMAINS[i.area]||{ar:"",en:""}))}</small></h3>
     ${cont?`<p class="tag warn" style="display:inline-block;margin-bottom:8px">${esc(t("contained"))} · ${esc(gate?gate.ref:"")}</p>`:""}
     <div class="walk"><div class="stg">${t("stage").map((s,k)=>`<span class="${k===i.st?"on":""}">${num(k+1)} ${esc(s)}</span>`).join("")}</div>
     ${i.d?`<p style="font-size:13.5px;white-space:pre-line">${esc(i.d)}</p>`:`<p class="mute" style="font-size:13px">${esc(tx({ar:"(سجل مثال؛ النص الكامل في نظام سديم)",en:"(example record; the full text lives in the SADEEM OS)"}))}</p>`}
     <div class="kv"><span>${esc(tx({ar:"المحطة الحالية",en:"Current station"}))}</span><b style="font-family:inherit">${esc(t("stage")[i.st])}</b><span>${esc(tx({ar:"ما يفتح المحطة التالية",en:"What opens the next station"}))}</span><b style="font-family:inherit;text-align:end">${esc(tx(GATES[Math.min(10,i.st)]))}</b><span>${esc(tx({ar:"الاحتياج الوطني",en:"National need"}))}</span><b>${esc(i.ch||"—")}</b><span>${esc(tx({ar:"الجهة المستلمة",en:"Receiving entity"}))}</span><b style="font-family:inherit">${esc(i.entity?tx(i.entity):"—")}</b></div>
     <div class="evalBox"><b style="font-size:12.5px">${esc(tx({ar:"التقييم وفق المعايير الوطنية (مقترح)",en:"National-criteria evaluation (proposed)"}))} · ${num(ns.total)}/100</b>
      ${CRIT.map(([k,l])=>`<div class="row"><span>${esc(tx(l))}</span><div class="bar ${k==="risk"?(ns.s[k]>50?"crit":"good"):""}"><i style="width:${ns.s[k]}%"></i></div><b>${num(ns.s[k])}</b></div>`).join("")}
      ${ns.ev.missing.length?`<ul style="margin:0;padding-inline-start:18px;font-size:13px;color:var(--ink2)">${ns.ev.missing.slice(0,3).map(m=>`<li>${esc(tx(m))}</li>`).join("")}</ul>`:""}</div>
     ${i.st>=5&&i.st<=7?`<div class="evalBox"><b style="font-size:12.5px">${esc(tx({ar:"جدول الأفكار: المقارنة قبل الإحالة",en:"Idea table: comparison before referral"}))}</b><div class="tblWrap"><table class="t"><thead><tr><th>ID</th><th>${esc(tx({ar:"الفكرة",en:"Idea"}))}</th><th>${esc(tx({ar:"النتيجة",en:"Score"}))}</th></tr></thead><tbody>${[i,...peers].map(x=>{const sc=natScore(x).total;return `<tr><td class="mono">${esc(x.id)}</td><td>${esc(isContained(x)&&!x.mine&&x!==i?tx({ar:"سجل محتوى",en:"Contained record"}):tx(x.t))}</td><td class="mono">${num(sc)}</td></tr>`}).join("")}</tbody></table></div></div>`:""}
     ${twins.length?`<p class="note">${esc(tx({ar:"أفكار مشابهة (فحص الازدواجية):",en:"Similar ideas (duplicate check):"}))} ${twins.map(x=>esc(x.i.id)+" "+num(Math.round(x.sim*100))+"%").join(" · ")}</p>`:""}
     <div style="display:flex;gap:8px;flex-wrap:wrap">${i.mine&&i.st<10?`<button class="btn sm" id="advance">${esc(tx({ar:"تحقق متطلب البوابة ← المحطة التالية",en:"Gate met → next station"}))}</button>`:""}${i.mine&&i.st===9?`<select id="ent" class="chip">${ENTITIES.map(e=>`<option value="${e.k}">${esc(tx(e))}</option>`).join("")}</select>`:""}<button class="btn ghost sm" id="support">${esc(tx({ar:"اطلب توجيهاً",en:"Request guidance"}))}</button><button class="btn ghost sm" id="toVault">${esc(tx({ar:"صنّف في قبو الاحتواء",en:"Classify in the vault"}))}</button></div></div>`;
    if($("#advance"))$("#advance").onclick=()=>{if(i.st===3&&!H.DB.gate.some(x=>x.idea===i.id&&x.by==="human-confirmed")){toast({ar:"محطة الاحتواء تحتاج تأكيد التصنيف في القبو أولاً",en:"The containment station needs a confirmed classification in the vault first"});return}
      if(i.st===9){const e=ENTITIES.find(x=>x.k===$("#ent").value);i.entity={ar:e.ar,en:e.en}}i.st++;i.days=0;H.save();window.FX&&FX.sound&&FX.sound("move");toast({ar:`انتقلت الفكرة إلى «${t("stage")[i.st]}»`,en:`Moved to '${t("stage")[i.st]}'`});render()};
    $("#support").onclick=()=>{i.support=(i.support||0)+1;H.save();toast({ar:"وصل طلب التوجيه إلى محللي سديم",en:"Guidance request sent to SADEEM analysts"})};
    $("#toVault").onclick=()=>{H.ctx.state={gateIdea:i.id};go("gate")};
    ai.set({object:"idea",state:{i,ns,twins}});
  }
  function renderWalk(){
    const box=$("#walkP");
    if(!walk){box.innerHTML=`<h3>${esc(tx({ar:"قدّم عبر نقطة الدخول الواحدة",en:"Submit through the single entry point"}))}</h3><p class="mute" style="font-size:13.5px;margin-bottom:12px">${esc(tx({ar:"خمس محطات موجّهة بدل نموذج واحد. المساعد يقيّم كل محطة ويبحث عن أفكار مشابهة قبل القبول، ويُفحص مستوى الحساسية تلقائياً.",en:"Five guided stations instead of one form. The assistant evaluates each station and looks for similar ideas before acceptance; sensitivity is screened automatically."}))}</p><button class="btn" id="startWalk">${esc(tx({ar:"ابدأ",en:"Start"}))}</button>`;$("#startWalk").onclick=()=>{walk={step:0,t:"",d:"",area:"land",src:"talent",ch:"",f:{}};renderWalk()};return}
    const s=STEPS[walk.step];const txt=walk.t+" "+Object.values(walk.f).join(" ");const ev=E.evaluate(txt,walk.ch);const tw=walk.step>=1?similar(txt):[];
    box.innerHTML=`<h3>${esc(tx({ar:"تقديم فكرة",en:"Submission"}))}<small>${num(walk.step+1)}/5</small></h3><div class="walk"><div class="stg">${STEPS.map((x,k)=>`<span class="${k===walk.step?"on":""}">${num(k+1)}</span>`).join("")}</div>
     ${walk.step===0?`<div class="field"><label for="wT">${esc(tx({ar:"عنوان الفكرة",en:"Idea title"}))}</label><input id="wT" value="${esc(walk.t)}"></div>`:""}
     <div class="field"><label for="wF">${esc(tx(s.l))}</label><textarea id="wF">${esc(walk.f[s.k]||"")}</textarea></div>
     ${walk.step===0?`<div class="grid g2" style="gap:10px"><div class="field"><label for="wS">${esc(tx({ar:"نوع المصدر",en:"Source type"}))}</label><select id="wS">${Object.entries(SOURCES).map(([k,v])=>`<option value="${k}" ${walk.src===k?"selected":""}>${esc(tx(v))}</option>`).join("")}</select></div><div class="field"><label for="wA">${esc(tx({ar:"المجال",en:"Domain"}))}</label><select id="wA">${Object.entries(DOMAINS).map(([k,v])=>`<option value="${k}" ${walk.area===k?"selected":""}>${esc(tx(v))}</option>`).join("")}</select></div></div><div class="field"><label for="wC">${esc(tx({ar:"الاحتياج الوطني (اختياري)",en:"National need (optional)"}))}</label><select id="wC"><option value="">—</option>${CHALLENGES.map(c=>`<option value="${c.id}" ${walk.ch===c.id?"selected":""}>${esc(c.id)} · ${esc(tx(c.t))}</option>`).join("")}</select></div>`:""}
     <div class="evalBox"><div class="row"><span>${esc(tx({ar:"جودة المدخل",en:"Input quality"}))}</span><div class="bar"><i style="width:${ev.total}%"></i></div><b>${num(ev.total)}</b></div><p style="font-size:12.5px;color:var(--ink2)">${esc(ev.missing[0]?tx(ev.missing[0]):tx({ar:"جيد. أكمل إلى المحطة التالية.",en:"Good. Continue to the next station."}))}</p>${tw.length?`<p style="font-size:12.5px;color:var(--warn)">${esc(tx({ar:"قد تكون مكررة مع:",en:"Possible duplicate of:"}))} ${tw.map(x=>esc(x.i.id)).join(", ")}</p>`:""}</div>
     <div style="display:flex;gap:8px;flex-wrap:wrap">${walk.step>0?`<button class="btn ghost sm" id="wBack">${esc(t("back"))}</button>`:""}<button class="btn sm" id="wNext">${walk.step<4?esc(t("next")):esc(tx({ar:"أرسل عبر نقطة الدخول",en:"Send through the entry point"}))}</button><button class="chip" id="wCancel">${esc(t("cancel"))}</button></div></div>`;
    const grab=()=>{walk.f[s.k]=$("#wF").value;if($("#wT"))walk.t=$("#wT").value;if($("#wC"))walk.ch=$("#wC").value;if($("#wA"))walk.area=$("#wA").value;if($("#wS"))walk.src=$("#wS").value};
    $("#wF").oninput=()=>{grab();ai.set({object:"walk",state:{walk}})};
    if($("#wBack"))$("#wBack").onclick=()=>{grab();walk.step--;renderWalk()};
    $("#wCancel").onclick=()=>{walk=null;renderWalk()};
    $("#wNext").onclick=()=>{grab();if(walk.step===0&&!walk.t.trim()){toast({ar:"أضف عنواناً",en:"Add a title"});return}if(walk.step<4){walk.step++;renderWalk();return}
      const d=STEPS.map(x=>`${tx(x.l)}\n${walk.f[x.k]||"—"}`).join("\n\n");const cls=E.classify(d+" "+walk.t,{});const dup=similar(walk.t+" "+d)[0];
      const it=addIdea({t:{ar:walk.t,en:walk.t},d,area:walk.area,src:walk.src,ch:walk.ch,st:0,dupOf:dup&&dup.sim>.5?dup.i.id:""});
      if(cls.level!=="open"){H.DB.gate.unshift({idea:it.id,level:cls.level,ref:"SV-"+H.uid(),at:Date.now(),rule:cls.rule,by:"keyword-screen"});H.save()}
      sel=it.id;walk=null;toast(cls.level==="high"?{ar:`استُلمت ${it.id} واحتُويت في القبو`,en:`${it.id} received and contained in the vault`}:{ar:`استُلمت الفكرة برقم ${it.id}`,en:`Received as ${it.id}`});render()};
    ai.set({object:"walk",state:{walk}});
  }
 },
 insight(c){
  if(c.object==="contained")return {role:{ar:"مساعد الاحتواء",en:"Containment assistant"},lines:[{ar:"هذا السجل محتوى. لا أقرأ نصه ولا أرسله إلى أي نموذج؛ أعرض المرجع والمحطة فقط.",en:"This record is contained. I do not read its text or send it to any model; I show the reference and station only."}]};
  if(c.object==="idea"&&c.state){const {i,ns,twins}=c.state;return {role:{ar:"المقيّم الوطني",en:"National assessor"},lines:[{ar:`${i.id} عند «${t("stage")[i.st]}» منذ ${num(i.days)} يوماً. التقييم المقترح ${num(ns.total)}/100.`,en:`${i.id} at '${t("stage")[i.st]}' for ${i.days} days. Proposed score ${ns.total}/100.`},{ar:`لفتح المحطة التالية: ${tx(GATES[Math.min(10,i.st)])}.`,en:`To open the next station: ${tx(GATES[Math.min(10,i.st)])}.`},twins&&twins.length?{ar:`تنبيه ازدواجية: تشبه ${twins.map(x=>x.i.id).join("، ")}.`,en:`Duplicate alert: resembles ${twins.map(x=>x.i.id).join(", ")}.`}:null,...ns.ev.missing.slice(0,1)].filter(Boolean)}}
  if(c.object==="walk"&&c.state&&c.state.walk){const w=c.state.walk;const ev=E.evaluate(w.t+" "+Object.values(w.f).join(" "),w.ch);return {role:{ar:"مدرّب التقديم",en:"Intake coach"},lines:[{ar:`المحطة ${num(w.step+1)} من ٥. الوضوح ${num(ev.s.clarity)}، القيمة ${num(ev.s.value)}، الجدوى ${num(ev.s.feasibility)}.`,en:`Station ${w.step+1} of 5. Clarity ${ev.s.clarity}, value ${ev.s.value}, feasibility ${ev.s.feasibility}.`},...ev.missing.slice(0,2),{ar:"صياغتك تبقى صياغتك؛ أقترح ولا أستبدل.",en:"Your wording stays yours; I suggest, I do not replace."}]}}
  if(c.object==="station"){const s=c.state;return {role:{ar:"المقيّم الوطني",en:"National assessor"},lines:[{ar:`محطة «${t("stage")[s]}»: بوابتها ${tx(GATES[s])}.`,en:`Station '${t("stage")[s]}': its gate is ${tx(GATES[s])}.`},{ar:t("proposed"),en:t("proposed")}]}}
  return {role:{ar:"المقيّم الوطني",en:"National assessor"},lines:[{ar:"اختر فكرة لتقييمها وفق المعايير الوطنية المقترحة، أو قدّم فكرة عبر نقطة الدخول الواحدة. المحطة الرابعة (الاحتواء) لا تُتجاوز دون تصنيف مؤكد.",en:"Select an idea to evaluate it on the proposed national criteria, or submit through the single entry point. Station four (containment) cannot be passed without a confirmed classification."}],actions:[{label:{ar:"قدّم فكرة",en:"Submit an idea"},run:()=>{const b=$("#startWalk");if(b)b.click()}}]}}
});

/* ---------- 04 CONTAINMENT VAULT ---------- */
register("gate",{
 mount(el){
  H.head(el,{ar:"قبو الاحتواء · 04",en:"Containment Vault · 04"},{ar:"الاحتواء قبل الإطلاق · التوجيه قبل التنفيذ · الحوكمة قبل التجربة",en:"Containment before launch · Guidance before execution · Governance before experiment"},{ar:"إدارة الابتكار عالي الحساسية في المجال التقني والدفاعي. تُصنَّف الفكرة هنا، وما يبلغ المستوى العالي يُختم ويُحجب ولا يُرسل إلى أي نموذج خارجي، ثم يُوجَّه عبر المسار الوطني.",en:"Management of high-sensitivity innovation in the technical and defence field. Ideas are classified here; anything at the high level is sealed, withheld and never sent to an external model, then guided through the national path."});
  const ideas=allIdeas().filter(i=>i.mine||!i.sens);const pre=(H.ctx.state&&H.ctx.state.gateIdea)||(ideas[0]&&ideas[0].id);let a={domain:0,dual:0,export:0,partner:0},pick=pre,res=null;
  el.insertAdjacentHTML("beforeend",`<div class="wrap gateGrid"><div><div class="vault" id="vault"><div><div class="lock"><svg class="i" style="width:26px;height:26px" viewBox="0 0 32 32"><path d="M16 1 L18.2 13.8 L31 16 L18.2 18.2 L16 31 L13.8 18.2 L1 16 L13.8 13.8 Z" fill="currentColor" stroke="none"/></svg></div><b style="font:600 12px var(--mono);letter-spacing:.24em;color:var(--brass2)">SADEEM · سديم</b><p style="margin-top:8px;font-size:13px;color:var(--onDark2)">${esc(tx({ar:"منصة ابتكار وطنية مركزية للابتكار التقني عالي الحساسية",en:"A national, centralised platform for high-sensitivity technical innovation"}))}</p></div><div class="seal"><div><b id="sealB">CONTAINED</b><span id="sealS"></span></div></div></div>
   <div class="principles"><div><b>${esc(tx({ar:"الاحتواء قبل الإطلاق",en:"Containment before launch"}))}</b>${esc(tx({ar:"لا إطلاق ولا تداول مفتوح؛ الفكرة تتشكّل وتُنقّى داخل فضاء منضبط.",en:"No launch and no open circulation; the idea takes shape inside a controlled space."}))}</div><div><b>${esc(tx({ar:"التوجيه قبل التنفيذ",en:"Guidance before execution"}))}</b>${esc(tx({ar:"تُوجَّه إلى الجهة الوطنية المختصة حسب احتياجات الدولة.",en:"Routed to the competent national entity according to the state's needs."}))}</div><div><b>${esc(tx({ar:"الحوكمة قبل التجربة",en:"Governance before experiment"}))}</b>${esc(tx({ar:"إطار سيادي محكوم بغرض التمكين.",en:"A sovereign framework governed for enablement."}))}</div></div>
   <p class="note" style="margin-top:12px">${esc(tx({ar:"مستويات التصنيف وقواعدها مقترحة، وتُستكمل حصرياً بموافقة رسمية.",en:"Classification levels and rules are proposed and are completed exclusively with official approval."}))}</p></div>
   <div class="panel"><h3>${esc(tx({ar:"تصنيف فكرة",en:"Classify an idea"}))}<small>${esc(tx({ar:"المساعد يقترح، الإنسان يؤكد",en:"the assistant recommends, a person confirms"}))}</small></h3>
    <div class="field"><label for="gI">${esc(tx({ar:"الفكرة",en:"Idea"}))}</label><select id="gI">${ideas.map(i=>`<option value="${esc(i.id)}" ${i.id===pre?"selected":""}>${esc(i.id)} · ${esc(tx(i.t))}</option>`).join("")}</select></div>
    <div class="qs">${[["domain",{ar:"مجال الفكرة",en:"Domain"},[{ar:"عام",en:"General"},{ar:"تقني حساس",en:"Sensitive technical"},{ar:"دفاعي",en:"Defence"}]],["dual",{ar:"استخدام مزدوج؟",en:"Dual use?"},[{ar:"لا",en:"No"},{ar:"نعم",en:"Yes"}]],["export",{ar:"تمسّ ضوابط التصدير أو بيانات مصنَّفة؟",en:"Touches export controls or classified data?"},[{ar:"لا",en:"No"},{ar:"نعم",en:"Yes"}]],["partner",{ar:"تتضمن بيانات جهة أخرى؟",en:"Includes another entity's data?"},[{ar:"لا",en:"No"},{ar:"نعم",en:"Yes"}]]].map(([k,l,o])=>`<div class="q"><b>${esc(tx(l))}</b><div class="seg" data-q="${k}">${o.map((x,i)=>`<button aria-pressed="${i===0}" data-v="${i}">${esc(tx(x))}</button>`).join("")}</div></div>`).join("")}</div>
    <div style="display:flex;gap:8px;margin-top:14px;flex-wrap:wrap"><button class="btn sm" id="gRun">${esc(tx({ar:"احسب التصنيف",en:"Compute classification"}))}</button><button class="btn brass sm" id="gConfirm" hidden>${esc(tx({ar:"أؤكد التصنيف",en:"Confirm classification"}))}</button></div>
    <div id="gOut" style="margin-top:14px"></div>
    <h3 style="margin-top:22px">${esc(tx({ar:"سجل الاحتواء والتوجيه",en:"Containment and routing log"}))}<small>${num(H.DB.gate.length)}</small></h3><div class="tblWrap"><table class="t"><thead><tr><th>${esc(tx({ar:"المرجع",en:"Ref"}))}</th><th>${esc(tx({ar:"الفكرة",en:"Idea"}))}</th><th>${esc(tx({ar:"المستوى",en:"Level"}))}</th><th>${esc(tx({ar:"بواسطة",en:"By"}))}</th></tr></thead><tbody>${H.DB.gate.map(g=>`<tr><td class="mono">${esc(g.ref)}</td><td class="mono">${esc(g.idea)}</td><td><span class="tag ${g.level==="high"?"warn":g.level==="controlled"?"sov":"good"}">${esc(g.level)}</span></td><td>${esc(g.by==="human-confirmed"?tx({ar:"تأكيد بشري",en:"Human-confirmed"}):tx({ar:"فحص آلي",en:"Automatic screen"}))}</td></tr>`).join("")||`<tr><td colspan="4" class="mute">—</td></tr>`}</tbody></table></div></div></div>`);
  $$(".seg[data-q] button").forEach(b=>b.onclick=()=>{const q=b.parentNode.dataset.q;a[q]=+b.dataset.v;$$("button",b.parentNode).forEach(x=>x.setAttribute("aria-pressed",x===b))});
  $("#gI").onchange=e=>pick=e.target.value;
  $("#gRun").onclick=()=>{const i=allIdeas().find(x=>x.id===pick);res=E.classify((i.d||"")+" "+tx(i.t),a);
    $("#gOut").innerHTML=`<div class="evalBox"><b>${esc(tx({ar:"التصنيف المقترح",en:"Recommended classification"}))}: <span class="tag ${res.level==="high"?"warn":res.level==="controlled"?"sov":"good"}">${esc(res.level)}</span> · ${num(res.pts)} pts${res.kw?" · "+esc(tx({ar:"كلمات حساسة رُصدت",en:"sensitive terms detected"})):""}</b><p style="font-size:13px;color:var(--ink2)">${esc(tx(res.rule))}</p></div>`;
    $("#gConfirm").hidden=false;ai.set({object:"class",state:res})};
  $("#gConfirm").onclick=()=>{if(!res)return;const ref="SV-"+H.uid();H.DB.gate=H.DB.gate.filter(g=>g.idea!==pick);H.DB.gate.unshift({idea:pick,level:res.level,ref,at:Date.now(),rule:res.rule,by:"human-confirmed"});H.save();
    const d=$("#vault");$("#sealB").textContent=res.level==="high"?"CONTAINED · محتواة":res.level==="controlled"?"CONTROLLED · موجَّهة":"OPEN · مفتوحة";$("#sealS").textContent=ref;d.classList.add("sealed");window.FX&&FX.sound&&FX.sound("seal");toast({ar:`سُجّل التصنيف ${ref}`,en:`Classification ${ref} recorded`});setTimeout(()=>H.go("gate"),2000)};
 },
 insight(c){if(c.object==="class"&&c.state){const r=c.state;return {role:{ar:"مساعد التصنيف (استشاري)",en:"Classification assistant (advisory)"},lines:[{ar:`المستوى المقترح: ${r.level}. ${tx(r.rule)}`,en:`Recommended level: ${r.level}. ${tx(r.rule)}`},{ar:"القرار للإنسان ويُسجَّل باسمه. السجلات المحتواة لا تظهر لغير المخوّلين.",en:"The decision is a person's and is recorded under their name. Contained records are hidden from anyone not authorised."}]}}
  return {role:{ar:"مساعد التصنيف (استشاري)",en:"Classification assistant (advisory)"},lines:[{ar:"أربعة أسئلة تكفي لاقتراح مستوى: مفتوح، موجّه، أو محتوى.",en:"Four questions are enough to recommend a level: open, controlled or contained."},{ar:`محتواة الآن: ${num(H.DB.gate.filter(g=>g.level==="high").length+allIdeas().filter(i=>i.sens==="high").length)}.`,en:`Contained now: ${H.DB.gate.filter(g=>g.level==="high").length+allIdeas().filter(i=>i.sens==="high").length}.`}]}}
});
})();
